# Auto-generated by scripts/generate_scanpy_proxies.py
from __future__ import annotations

import inspect

import scanpy.metrics as _orig_module

__all__ = [
    "confusion_matrix",
    "gearys_c",
    "morans_i"
]

def confusion_matrix(orig: 'pd.Series | np.ndarray | Sequence', new: 'pd.Series | np.ndarray | Sequence', data: 'pd.DataFrame | None' = None, *, normalize: 'bool' = True, **_lotus_extras) -> 'pd.DataFrame':
    _lotus_kwargs = {}
    if normalize != True:
        _lotus_kwargs['normalize'] = normalize
    _lotus_call_args = []
    _lotus_call_args.append(orig)
    _lotus_call_args.append(new)
    _lotus_call_args.append(data)
    return _orig_module.confusion_matrix(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def gearys_c(adata_or_graph: 'AnnData | CSRBase', /, vals: '_Vals | None' = None, *, use_graph: 'str | None' = None, layer: 'str | None' = None, obsm: 'str | None' = None, obsp: 'str | None' = None, use_raw: 'bool' = False, **_lotus_extras) -> 'np.ndarray | float':
    _lotus_kwargs = {}
    if use_graph is not None:
        _lotus_kwargs['use_graph'] = use_graph
    if layer is not None:
        _lotus_kwargs['layer'] = layer
    if obsm is not None:
        _lotus_kwargs['obsm'] = obsm
    if obsp is not None:
        _lotus_kwargs['obsp'] = obsp
    if use_raw != False:
        _lotus_kwargs['use_raw'] = use_raw
    _lotus_call_args = []
    _lotus_call_args.append(adata_or_graph)
    _lotus_call_args.append(vals)
    return _orig_module.gearys_c(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def morans_i(adata_or_graph: 'AnnData | CSRBase', /, vals: '_Vals | None' = None, *, use_graph: 'str | None' = None, layer: 'str | None' = None, obsm: 'str | None' = None, obsp: 'str | None' = None, use_raw: 'bool' = False, **_lotus_extras) -> 'np.ndarray | float':
    _lotus_kwargs = {}
    if use_graph is not None:
        _lotus_kwargs['use_graph'] = use_graph
    if layer is not None:
        _lotus_kwargs['layer'] = layer
    if obsm is not None:
        _lotus_kwargs['obsm'] = obsm
    if obsp is not None:
        _lotus_kwargs['obsp'] = obsp
    if use_raw != False:
        _lotus_kwargs['use_raw'] = use_raw
    _lotus_call_args = []
    _lotus_call_args.append(adata_or_graph)
    _lotus_call_args.append(vals)
    return _orig_module.morans_i(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def __getattr__(name: str):
    try:
        return getattr(_orig_module, name)
    except AttributeError as exc:
        raise AttributeError(f"scanpy.metrics has no attribute {name!r}") from exc

def __dir__():
    return sorted(set(__all__) | {name for name in dir(_orig_module) if not name.startswith('__')})
