# Auto-generated by scripts/generate_scanpy_proxies.py
from __future__ import annotations

import inspect

import scanpy._utils.compute.is_constant as _orig_module

__all__ = [
    "is_constant",
    "njit"
]

def is_constant(a: 'NDArray' = None, axis: 'Literal[0, 1] | None' = None, **_lotus_extras) -> 'bool | NDArray[np.bool_]':
    _lotus_call_args = []
    if a is not None:
        _lotus_call_args.append(a)
    _lotus_call_args.append(axis)
    return _orig_module.is_constant(*_lotus_call_args, **_lotus_extras)

def njit(fn: 'Callable[P, R] | None' = None, /, **_lotus_extras) -> 'Callable[P, R] | Callable[[Callable[P, R]], Callable[P, R]]':
    _lotus_call_args = []
    _lotus_call_args.append(fn)
    return _orig_module.njit(*_lotus_call_args, **_lotus_extras)

def __getattr__(name: str):
    try:
        return getattr(_orig_module, name)
    except AttributeError as exc:
        raise AttributeError(f"scanpy._utils.compute.is_constant has no attribute {name!r}") from exc

def __dir__():
    return sorted(set(__all__) | {name for name in dir(_orig_module) if not name.startswith('__')})
