services:
  - type: web
    name: lotus-api
    env: python
    buildCommand: pip install -r requirements.txt && pip install -e .
    startCommand: gunicorn lotus.api.app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GUNICORN
        value: "true"

