services:
  - type: web
    name: lotus-api
    env: python
    pythonVersion: "3.10"
    buildCommand: pip install --upgrade pip && pip install -r requirements-render.txt && pip install -e .
    startCommand: gunicorn lotus.api.app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: GUNICORN
        value: "true"

