# Auto-generated by scripts/generate_scanpy_proxies.py
from __future__ import annotations

import inspect

import scanpy.cli as _orig_module

__all__ = [
    "console_main",
    "main"
]

def console_main(**_lotus_extras):
    _lotus_call_args = []
    return _orig_module.console_main(*_lotus_call_args, **_lotus_extras)

def main(argv: 'Sequence[str] | None' = None, *, check: 'bool' = True, **runargs) -> 'CompletedProcess | None':
    _lotus_kwargs = {}
    if check != True:
        _lotus_kwargs['check'] = check
    _lotus_kwargs.update(runargs)
    return _orig_module.main(argv, **_lotus_kwargs)

def __getattr__(name: str):
    try:
        return getattr(_orig_module, name)
    except AttributeError as exc:
        raise AttributeError(f"scanpy.cli has no attribute {name!r}") from exc

def __dir__():
    return sorted(set(__all__) | {name for name in dir(_orig_module) if not name.startswith('__')})
