# Auto-generated by scripts/generate_scanpy_proxies.py
from __future__ import annotations

import inspect

import scanpy.preprocessing._scrublet.core as _orig_module

__all__ = [
    "Neighbors",
    "Scrublet",
    "sample_comb",
    "subsample_counts"
]

class Neighbors(_orig_module.Neighbors):
    def __init__(self, adata: 'AnnData', *, n_dcs: 'int | None' = None, neighbors_key: 'str | None' = None):
        super().__init__(adata, n_dcs=n_dcs, neighbors_key=neighbors_key)

class Scrublet(_orig_module.Scrublet):
    def __init__(self, counts_obs: 'InitVar[CSBase | NDArray[np.integer]]', *, total_counts_obs: 'InitVar[NDArray[np.integer] | None]' = None, sim_doublet_ratio: 'float' = 2.0, n_neighbors: 'InitVar[int | None]' = None, expected_doublet_rate: 'float' = 0.1, stdev_doublet_rate: 'float' = 0.02, random_state: 'InitVar[_LegacyRandom]' = 0) -> None:
        super().__init__(counts_obs, total_counts_obs=total_counts_obs, sim_doublet_ratio=sim_doublet_ratio, n_neighbors=n_neighbors, expected_doublet_rate=expected_doublet_rate, stdev_doublet_rate=stdev_doublet_rate, random_state=random_state)

def sample_comb(dims: 'tuple[int, ...]', nsamp: 'int', *, random_state: '_LegacyRandom' = None, method: "Literal['auto', 'tracking_selection', 'reservoir_sampling', 'pool']" = 'auto', **_lotus_extras) -> 'NDArray[np.int64]':
    _lotus_kwargs = {}
    if random_state is not None:
        _lotus_kwargs['random_state'] = random_state
    if method != 'auto':
        _lotus_kwargs['method'] = method
    _lotus_call_args = []
    _lotus_call_args.append(dims)
    _lotus_call_args.append(nsamp)
    return _orig_module.sample_comb(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def subsample_counts(e: 'CSBase', /, *, rate: 'float', original_totals, random_seed: '_LegacyRandom' = 0, **_lotus_extras) -> 'tuple[CSBase, NDArray[np.int64]]':
    _lotus_kwargs = {}
    _lotus_kwargs['rate'] = rate
    _lotus_kwargs['original_totals'] = original_totals
    if random_seed != 0:
        _lotus_kwargs['random_seed'] = random_seed
    _lotus_call_args = []
    _lotus_call_args.append(e)
    return _orig_module.subsample_counts(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def __getattr__(name: str):
    try:
        return getattr(_orig_module, name)
    except AttributeError as exc:
        raise AttributeError(f"scanpy.preprocessing._scrublet.core has no attribute {name!r}") from exc

def __dir__():
    return sorted(set(__all__) | {name for name in dir(_orig_module) if not name.startswith('__')})
