# Auto-generated by scripts/generate_scanpy_proxies.py
from __future__ import annotations

import inspect

import scanpy.preprocessing._scrublet.pipeline as _orig_module

__all__ = [
    "mean_center",
    "normalize_variance",
    "pca",
    "sparse_multiply",
    "sparse_zscore",
    "truncated_svd",
    "zscore"
]

def mean_center(self: 'Scrublet' = None, **_lotus_extras) -> 'None':
    _lotus_call_args = []
    if self is not None:
        _lotus_call_args.append(self)
    return _orig_module.mean_center(*_lotus_call_args, **_lotus_extras)

def normalize_variance(self: 'Scrublet' = None, **_lotus_extras) -> 'None':
    _lotus_call_args = []
    if self is not None:
        _lotus_call_args.append(self)
    return _orig_module.normalize_variance(*_lotus_call_args, **_lotus_extras)

def pca(self: 'Scrublet' = None, n_prin_comps: 'int' = 50, *, random_state: '_LegacyRandom' = 0, svd_solver: "Literal['auto', 'full', 'arpack', 'randomized']" = 'arpack', **_lotus_extras) -> 'None':
    _lotus_kwargs = {}
    if random_state != 0:
        _lotus_kwargs['random_state'] = random_state
    if svd_solver != 'arpack':
        _lotus_kwargs['svd_solver'] = svd_solver
    _lotus_call_args = []
    if self is not None:
        _lotus_call_args.append(self)
    _lotus_call_args.append(n_prin_comps)
    return _orig_module.pca(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def sparse_multiply(e: 'CSBase | NDArray[np.float64]', a: 'float | NDArray[np.float64]', /, **_lotus_extras) -> 'CSBase':
    _lotus_call_args = []
    _lotus_call_args.append(e)
    _lotus_call_args.append(a)
    return _orig_module.sparse_multiply(*_lotus_call_args, **_lotus_extras)

def sparse_zscore(e: 'CSBase', /, *, gene_mean: 'NDArray[np.float64] | None' = None, gene_stdev: 'NDArray[np.float64] | None' = None, **_lotus_extras) -> 'CSBase':
    _lotus_kwargs = {}
    if gene_mean is not None:
        _lotus_kwargs['gene_mean'] = gene_mean
    if gene_stdev is not None:
        _lotus_kwargs['gene_stdev'] = gene_stdev
    _lotus_call_args = []
    _lotus_call_args.append(e)
    return _orig_module.sparse_zscore(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def truncated_svd(self: 'Scrublet' = None, n_prin_comps: 'int' = 30, *, random_state: '_LegacyRandom' = 0, algorithm: "Literal['arpack', 'randomized']" = 'arpack', **_lotus_extras) -> 'None':
    _lotus_kwargs = {}
    if random_state != 0:
        _lotus_kwargs['random_state'] = random_state
    if algorithm != 'arpack':
        _lotus_kwargs['algorithm'] = algorithm
    _lotus_call_args = []
    if self is not None:
        _lotus_call_args.append(self)
    _lotus_call_args.append(n_prin_comps)
    return _orig_module.truncated_svd(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def zscore(self: 'Scrublet' = None, **_lotus_extras) -> 'None':
    _lotus_call_args = []
    if self is not None:
        _lotus_call_args.append(self)
    return _orig_module.zscore(*_lotus_call_args, **_lotus_extras)

def __getattr__(name: str):
    try:
        return getattr(_orig_module, name)
    except AttributeError as exc:
        raise AttributeError(f"scanpy.preprocessing._scrublet.pipeline has no attribute {name!r}") from exc

def __dir__():
    return sorted(set(__all__) | {name for name in dir(_orig_module) if not name.startswith('__')})
