# Auto-generated by scripts/generate_scanpy_proxies.py
from __future__ import annotations

import inspect

import scanpy.preprocessing._scrublet.sparse_utils as _orig_module

__all__ = [
    "sparse_multiply",
    "sparse_zscore",
    "subsample_counts"
]

def sparse_multiply(e: 'CSBase | NDArray[np.float64]', a: 'float | NDArray[np.float64]', /, **_lotus_extras) -> 'CSBase':
    _lotus_call_args = []
    _lotus_call_args.append(e)
    _lotus_call_args.append(a)
    return _orig_module.sparse_multiply(*_lotus_call_args, **_lotus_extras)

def sparse_zscore(e: 'CSBase', /, *, gene_mean: 'NDArray[np.float64] | None' = None, gene_stdev: 'NDArray[np.float64] | None' = None, **_lotus_extras) -> 'CSBase':
    _lotus_kwargs = {}
    if gene_mean is not None:
        _lotus_kwargs['gene_mean'] = gene_mean
    if gene_stdev is not None:
        _lotus_kwargs['gene_stdev'] = gene_stdev
    _lotus_call_args = []
    _lotus_call_args.append(e)
    return _orig_module.sparse_zscore(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def subsample_counts(e: 'CSBase', /, *, rate: 'float', original_totals, random_seed: '_LegacyRandom' = 0, **_lotus_extras) -> 'tuple[CSBase, NDArray[np.int64]]':
    _lotus_kwargs = {}
    _lotus_kwargs['rate'] = rate
    _lotus_kwargs['original_totals'] = original_totals
    if random_seed != 0:
        _lotus_kwargs['random_seed'] = random_seed
    _lotus_call_args = []
    _lotus_call_args.append(e)
    return _orig_module.subsample_counts(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def __getattr__(name: str):
    try:
        return getattr(_orig_module, name)
    except AttributeError as exc:
        raise AttributeError(f"scanpy.preprocessing._scrublet.sparse_utils has no attribute {name!r}") from exc

def __dir__():
    return sorted(set(__all__) | {name for name in dir(_orig_module) if not name.startswith('__')})
