# Auto-generated by scripts/generate_scanpy_proxies.py
from __future__ import annotations

import inspect

import scanpy.plotting._tools.paga as _orig_module

__all__ = [
    "coerce_fa2_layout",
    "fa2_positions",
    "matrix",
    "paga",
    "paga_adjacency",
    "paga_compare",
    "paga_path",
    "settings"
]

def coerce_fa2_layout(layout: 'S' = None, **_lotus_extras) -> "S | Literal['fa', 'fr']":
    _lotus_call_args = []
    if layout is not None:
        _lotus_call_args.append(layout)
    return _orig_module.coerce_fa2_layout(*_lotus_call_args, **_lotus_extras)

def fa2_positions(adjacency: 'SpBase | np.ndarray', init_coords: 'np.ndarray', **kwds) -> 'list[tuple[float, float]]':
    _lotus_kwargs = {}
    _lotus_kwargs.update(kwds)
    return _orig_module.fa2_positions(adjacency, init_coords, **_lotus_kwargs)

def matrix(matrix: 'ArrayLike | Image' = None, *, xlabel: 'str | None' = None, ylabel: 'str | None' = None, xticks: 'Collection[str] | None' = None, yticks: 'Collection[str] | None' = None, title: 'str | None' = None, colorbar_shrink: 'float' = 0.5, color_map: 'str | Colormap | None' = None, show: 'bool | None' = None, save: 'bool | str | None' = None, ax: 'Axes | None' = None, **_lotus_extras) -> 'None':
    _lotus_kwargs = {}
    if xlabel is not None:
        _lotus_kwargs['xlabel'] = xlabel
    if ylabel is not None:
        _lotus_kwargs['ylabel'] = ylabel
    if xticks is not None:
        _lotus_kwargs['xticks'] = xticks
    if yticks is not None:
        _lotus_kwargs['yticks'] = yticks
    if title is not None:
        _lotus_kwargs['title'] = title
    if colorbar_shrink != 0.5:
        _lotus_kwargs['colorbar_shrink'] = colorbar_shrink
    if color_map is not None:
        _lotus_kwargs['color_map'] = color_map
    if show is not None:
        _lotus_kwargs['show'] = show
    if save is not None:
        _lotus_kwargs['save'] = save
    if ax is not None:
        _lotus_kwargs['ax'] = ax
    _lotus_call_args = []
    if matrix is not None:
        _lotus_call_args.append(matrix)
    return _orig_module.matrix(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

_paga_layout_kwds_default = inspect.signature(_orig_module.paga).parameters['layout_kwds'].default
_paga_text_kwds_default = inspect.signature(_orig_module.paga).parameters['text_kwds'].default
_paga_cb_kwds_default = inspect.signature(_orig_module.paga).parameters['cb_kwds'].default

def paga(adata: 'AnnData' = None, *, threshold: 'float | None' = None, color: 'str | Mapping[str | int, Mapping[Any, float]] | None' = None, layout: '_Layout | None' = None, layout_kwds: 'Mapping[str, Any]' = _paga_layout_kwds_default, init_pos: 'np.ndarray | None' = None, root: 'int | str | Sequence[int] | None' = 0, labels: 'str | Sequence[str] | Mapping[str, str] | None' = None, single_component: 'bool' = False, solid_edges: 'str' = 'connectivities', dashed_edges: 'str | None' = None, transitions: 'str | None' = None, fontsize: 'int | None' = None, fontweight: 'str' = 'bold', fontoutline: 'int | None' = None, text_kwds: 'Mapping[str, Any]' = _paga_text_kwds_default, node_size_scale: 'float' = 1.0, node_size_power: 'float' = 0.5, edge_width_scale: 'float' = 1.0, min_edge_width: 'float | None' = None, max_edge_width: 'float | None' = None, arrowsize: 'int' = 30, title: 'str | None' = None, left_margin: 'float' = 0.01, random_state: 'int | None' = 0, pos: 'np.ndarray | Path | str | None' = None, normalize_to_color: 'bool' = False, cmap: 'str | Colormap | None' = None, cax: 'Axes | None' = None, colorbar=None, cb_kwds: 'Mapping[str, Any]' = _paga_cb_kwds_default, frameon: 'bool | None' = None, add_pos: 'bool' = True, export_to_gexf: 'bool' = False, use_raw: 'bool' = True, colors=None, groups=None, plot: 'bool' = True, show: 'bool | None' = None, save: 'bool | str | None' = None, ax: 'Axes | None' = None, **_lotus_extras) -> 'Axes | list[Axes] | None':
    _lotus_kwargs = {}
    if threshold is not None:
        _lotus_kwargs['threshold'] = threshold
    if color is not None:
        _lotus_kwargs['color'] = color
    if layout is not None:
        _lotus_kwargs['layout'] = layout
    if layout_kwds is not _paga_layout_kwds_default:
        _lotus_kwargs['layout_kwds'] = layout_kwds
    if init_pos is not None:
        _lotus_kwargs['init_pos'] = init_pos
    if root != 0:
        _lotus_kwargs['root'] = root
    if labels is not None:
        _lotus_kwargs['labels'] = labels
    if single_component != False:
        _lotus_kwargs['single_component'] = single_component
    if solid_edges != 'connectivities':
        _lotus_kwargs['solid_edges'] = solid_edges
    if dashed_edges is not None:
        _lotus_kwargs['dashed_edges'] = dashed_edges
    if transitions is not None:
        _lotus_kwargs['transitions'] = transitions
    if fontsize is not None:
        _lotus_kwargs['fontsize'] = fontsize
    if fontweight != 'bold':
        _lotus_kwargs['fontweight'] = fontweight
    if fontoutline is not None:
        _lotus_kwargs['fontoutline'] = fontoutline
    if text_kwds is not _paga_text_kwds_default:
        _lotus_kwargs['text_kwds'] = text_kwds
    if node_size_scale != 1.0:
        _lotus_kwargs['node_size_scale'] = node_size_scale
    if node_size_power != 0.5:
        _lotus_kwargs['node_size_power'] = node_size_power
    if edge_width_scale != 1.0:
        _lotus_kwargs['edge_width_scale'] = edge_width_scale
    if min_edge_width is not None:
        _lotus_kwargs['min_edge_width'] = min_edge_width
    if max_edge_width is not None:
        _lotus_kwargs['max_edge_width'] = max_edge_width
    if arrowsize != 30:
        _lotus_kwargs['arrowsize'] = arrowsize
    if title is not None:
        _lotus_kwargs['title'] = title
    if left_margin != 0.01:
        _lotus_kwargs['left_margin'] = left_margin
    if random_state != 0:
        _lotus_kwargs['random_state'] = random_state
    if pos is not None:
        _lotus_kwargs['pos'] = pos
    if normalize_to_color != False:
        _lotus_kwargs['normalize_to_color'] = normalize_to_color
    if cmap is not None:
        _lotus_kwargs['cmap'] = cmap
    if cax is not None:
        _lotus_kwargs['cax'] = cax
    if colorbar is not None:
        _lotus_kwargs['colorbar'] = colorbar
    if cb_kwds is not _paga_cb_kwds_default:
        _lotus_kwargs['cb_kwds'] = cb_kwds
    if frameon is not None:
        _lotus_kwargs['frameon'] = frameon
    if add_pos != True:
        _lotus_kwargs['add_pos'] = add_pos
    if export_to_gexf != False:
        _lotus_kwargs['export_to_gexf'] = export_to_gexf
    if use_raw != True:
        _lotus_kwargs['use_raw'] = use_raw
    if colors is not None:
        _lotus_kwargs['colors'] = colors
    if groups is not None:
        _lotus_kwargs['groups'] = groups
    if plot != True:
        _lotus_kwargs['plot'] = plot
    if show is not None:
        _lotus_kwargs['show'] = show
    if save is not None:
        _lotus_kwargs['save'] = save
    if ax is not None:
        _lotus_kwargs['ax'] = ax
    _lotus_call_args = []
    if adata is not None:
        _lotus_call_args.append(adata)
    return _orig_module.paga(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def paga_adjacency(adata: 'AnnData' = None, *, adjacency: 'str' = 'connectivities', adjacency_tree: 'str' = 'connectivities_tree', as_heatmap: 'bool' = True, color_map: 'str | Colormap | None' = None, show: 'bool | None' = None, save: 'bool | str | None' = None, **_lotus_extras) -> 'None':
    _lotus_kwargs = {}
    if adjacency != 'connectivities':
        _lotus_kwargs['adjacency'] = adjacency
    if adjacency_tree != 'connectivities_tree':
        _lotus_kwargs['adjacency_tree'] = adjacency_tree
    if as_heatmap != True:
        _lotus_kwargs['as_heatmap'] = as_heatmap
    if color_map is not None:
        _lotus_kwargs['color_map'] = color_map
    if show is not None:
        _lotus_kwargs['show'] = show
    if save is not None:
        _lotus_kwargs['save'] = save
    _lotus_call_args = []
    if adata is not None:
        _lotus_call_args.append(adata)
    return _orig_module.paga_adjacency(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def paga_compare(adata: 'AnnData', basis=None, *, edges=False, color=None, alpha=None, groups=None, components=None, projection: "Literal['2d', '3d']" = '2d', legend_loc: '_LegendLoc | None' = 'on data', legend_fontsize: 'float | _FontSize | None' = None, legend_fontweight: 'int | _FontWeight' = 'bold', legend_fontoutline=None, color_map=None, palette=None, frameon=False, size=None, title=None, right_margin=None, left_margin=0.05, show=None, save=None, title_graph=None, groups_graph=None, pos=None, **paga_graph_params):
    _lotus_kwargs = {}
    if edges != False:
        _lotus_kwargs['edges'] = edges
    if color is not None:
        _lotus_kwargs['color'] = color
    if alpha is not None:
        _lotus_kwargs['alpha'] = alpha
    if groups is not None:
        _lotus_kwargs['groups'] = groups
    if components is not None:
        _lotus_kwargs['components'] = components
    if projection != '2d':
        _lotus_kwargs['projection'] = projection
    if legend_loc != 'on data':
        _lotus_kwargs['legend_loc'] = legend_loc
    if legend_fontsize is not None:
        _lotus_kwargs['legend_fontsize'] = legend_fontsize
    if legend_fontweight != 'bold':
        _lotus_kwargs['legend_fontweight'] = legend_fontweight
    if legend_fontoutline is not None:
        _lotus_kwargs['legend_fontoutline'] = legend_fontoutline
    if color_map is not None:
        _lotus_kwargs['color_map'] = color_map
    if palette is not None:
        _lotus_kwargs['palette'] = palette
    if frameon != False:
        _lotus_kwargs['frameon'] = frameon
    if size is not None:
        _lotus_kwargs['size'] = size
    if title is not None:
        _lotus_kwargs['title'] = title
    if right_margin is not None:
        _lotus_kwargs['right_margin'] = right_margin
    if left_margin != 0.05:
        _lotus_kwargs['left_margin'] = left_margin
    if show is not None:
        _lotus_kwargs['show'] = show
    if save is not None:
        _lotus_kwargs['save'] = save
    if title_graph is not None:
        _lotus_kwargs['title_graph'] = title_graph
    if groups_graph is not None:
        _lotus_kwargs['groups_graph'] = groups_graph
    if pos is not None:
        _lotus_kwargs['pos'] = pos
    _lotus_kwargs.update(paga_graph_params)
    return _orig_module.paga_compare(adata, basis, **_lotus_kwargs)

_paga_path_color_maps_annotations_default = inspect.signature(_orig_module.paga_path).parameters['color_maps_annotations'].default

def paga_path(adata: 'AnnData', nodes: 'Sequence[str | int]', keys: 'Sequence[str]', *, use_raw: 'bool' = True, annotations: 'Sequence[str]' = ('dpt_pseudotime',), color_map: 'str | Colormap | None' = None, color_maps_annotations: 'Mapping[str, str | Colormap]' = _paga_path_color_maps_annotations_default, palette_groups: 'Sequence[str] | None' = None, n_avg: 'int' = 1, groups_key: 'str | None' = None, xlim: 'tuple[int | None, int | None]' = (None, None), title: 'str | None' = None, left_margin=None, ytick_fontsize: 'int | None' = None, title_fontsize: 'int | None' = None, show_node_names: 'bool' = True, show_yticks: 'bool' = True, show_colorbar: 'bool' = True, legend_fontsize: 'float | _FontSize | None' = None, legend_fontweight: 'int | _FontWeight | None' = None, normalize_to_zero_one: 'bool' = False, as_heatmap: 'bool' = True, return_data: 'bool' = False, show: 'bool | None' = None, save: 'bool | str | None' = None, ax: 'Axes | None' = None, **_lotus_extras) -> 'tuple[Axes, pd.DataFrame] | Axes | pd.DataFrame | None':
    _lotus_kwargs = {}
    if use_raw != True:
        _lotus_kwargs['use_raw'] = use_raw
    if annotations != ('dpt_pseudotime',):
        _lotus_kwargs['annotations'] = annotations
    if color_map is not None:
        _lotus_kwargs['color_map'] = color_map
    if color_maps_annotations is not _paga_path_color_maps_annotations_default:
        _lotus_kwargs['color_maps_annotations'] = color_maps_annotations
    if palette_groups is not None:
        _lotus_kwargs['palette_groups'] = palette_groups
    if n_avg != 1:
        _lotus_kwargs['n_avg'] = n_avg
    if groups_key is not None:
        _lotus_kwargs['groups_key'] = groups_key
    if xlim != (None, None):
        _lotus_kwargs['xlim'] = xlim
    if title is not None:
        _lotus_kwargs['title'] = title
    if left_margin is not None:
        _lotus_kwargs['left_margin'] = left_margin
    if ytick_fontsize is not None:
        _lotus_kwargs['ytick_fontsize'] = ytick_fontsize
    if title_fontsize is not None:
        _lotus_kwargs['title_fontsize'] = title_fontsize
    if show_node_names != True:
        _lotus_kwargs['show_node_names'] = show_node_names
    if show_yticks != True:
        _lotus_kwargs['show_yticks'] = show_yticks
    if show_colorbar != True:
        _lotus_kwargs['show_colorbar'] = show_colorbar
    if legend_fontsize is not None:
        _lotus_kwargs['legend_fontsize'] = legend_fontsize
    if legend_fontweight is not None:
        _lotus_kwargs['legend_fontweight'] = legend_fontweight
    if normalize_to_zero_one != False:
        _lotus_kwargs['normalize_to_zero_one'] = normalize_to_zero_one
    if as_heatmap != True:
        _lotus_kwargs['as_heatmap'] = as_heatmap
    if return_data != False:
        _lotus_kwargs['return_data'] = return_data
    if show is not None:
        _lotus_kwargs['show'] = show
    if save is not None:
        _lotus_kwargs['save'] = save
    if ax is not None:
        _lotus_kwargs['ax'] = ax
    _lotus_call_args = []
    _lotus_call_args.append(adata)
    _lotus_call_args.append(nodes)
    _lotus_call_args.append(keys)
    return _orig_module.paga_path(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

class settings(_orig_module.settings):
    def __init__(self, /, *args, **kwargs):
        super().__init__(*args, **kwargs)

def __getattr__(name: str):
    try:
        return getattr(_orig_module, name)
    except AttributeError as exc:
        raise AttributeError(f"scanpy.plotting._tools.paga has no attribute {name!r}") from exc

def __dir__():
    return sorted(set(__all__) | {name for name in dir(_orig_module) if not name.startswith('__')})
