# Auto-generated by scripts/generate_scanpy_proxies.py
from __future__ import annotations

import inspect

import scanpy.get.get as _orig_module

__all__ = [
    "obs_df",
    "rank_genes_groups_df",
    "var_df"
]

def obs_df(adata: 'AnnData' = None, keys: 'Collection[str]' = (), obsm_keys: 'Iterable[tuple[str, int]]' = (), *, layer: 'str | None' = None, gene_symbols: 'str | None' = None, use_raw: 'bool' = False, **_lotus_extras) -> 'pd.DataFrame':
    _lotus_kwargs = {}
    if layer is not None:
        _lotus_kwargs['layer'] = layer
    if gene_symbols is not None:
        _lotus_kwargs['gene_symbols'] = gene_symbols
    if use_raw != False:
        _lotus_kwargs['use_raw'] = use_raw
    _lotus_call_args = []
    if adata is not None:
        _lotus_call_args.append(adata)
    _lotus_call_args.append(keys)
    _lotus_call_args.append(obsm_keys)
    return _orig_module.obs_df(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def rank_genes_groups_df(adata: 'AnnData', group: 'str | Iterable[str] | None', *, key: 'str' = 'rank_genes_groups', pval_cutoff: 'float | None' = None, log2fc_min: 'float | None' = None, log2fc_max: 'float | None' = None, gene_symbols: 'str | None' = None, **_lotus_extras) -> 'pd.DataFrame':
    _lotus_kwargs = {}
    if key != 'rank_genes_groups':
        _lotus_kwargs['key'] = key
    if pval_cutoff is not None:
        _lotus_kwargs['pval_cutoff'] = pval_cutoff
    if log2fc_min is not None:
        _lotus_kwargs['log2fc_min'] = log2fc_min
    if log2fc_max is not None:
        _lotus_kwargs['log2fc_max'] = log2fc_max
    if gene_symbols is not None:
        _lotus_kwargs['gene_symbols'] = gene_symbols
    _lotus_call_args = []
    _lotus_call_args.append(adata)
    _lotus_call_args.append(group)
    return _orig_module.rank_genes_groups_df(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def var_df(adata: 'AnnData' = None, keys: 'Collection[str]' = (), varm_keys: 'Iterable[tuple[str, int]]' = (), *, layer: 'str | None' = None, **_lotus_extras) -> 'pd.DataFrame':
    _lotus_kwargs = {}
    if layer is not None:
        _lotus_kwargs['layer'] = layer
    _lotus_call_args = []
    if adata is not None:
        _lotus_call_args.append(adata)
    _lotus_call_args.append(keys)
    _lotus_call_args.append(varm_keys)
    return _orig_module.var_df(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def __getattr__(name: str):
    try:
        return getattr(_orig_module, name)
    except AttributeError as exc:
        raise AttributeError(f"scanpy.get.get has no attribute {name!r}") from exc

def __dir__():
    return sorted(set(__all__) | {name for name in dir(_orig_module) if not name.startswith('__')})
