# Auto-generated by scripts/generate_scanpy_proxies.py
from __future__ import annotations

import inspect

import scanpy._settings.verbosity as _orig_module

__all__ = [
    "Verbosity",
    "VerbosityMeta"
]

Verbosity = _orig_module.Verbosity  # Proxy alias for scanpy._settings.verbosity.Verbosity

class VerbosityMeta(_orig_module.VerbosityMeta):
    def __init__(self, /, *args, **kwargs):
        super().__init__(*args, **kwargs)

def __getattr__(name: str):
    try:
        return getattr(_orig_module, name)
    except AttributeError as exc:
        raise AttributeError(f"scanpy._settings.verbosity has no attribute {name!r}") from exc

def __dir__():
    return sorted(set(__all__) | {name for name in dir(_orig_module) if not name.startswith('__')})
