# Auto-generated by scripts/generate_scanpy_proxies.py
from __future__ import annotations

import inspect

import scanpy.preprocessing._deprecated.highly_variable_genes as _orig_module

__all__ = [
    "filter_genes_cv_deprecated",
    "filter_genes_dispersion",
    "filter_genes_fano_deprecated",
    "materialize_as_ndarray"
]

def filter_genes_cv_deprecated(x, /, e_cutoff, cv_filter, **_lotus_extras):
    _lotus_call_args = []
    _lotus_call_args.append(x)
    _lotus_call_args.append(e_cutoff)
    _lotus_call_args.append(cv_filter)
    return _orig_module.filter_genes_cv_deprecated(*_lotus_call_args, **_lotus_extras)

def filter_genes_dispersion(data: 'AnnData | CSBase | np.ndarray' = None, *, flavor: "Literal['seurat', 'cell_ranger']" = 'seurat', min_disp: 'float | None' = None, max_disp: 'float | None' = None, min_mean: 'float | None' = None, max_mean: 'float | None' = None, n_bins: 'int' = 20, n_top_genes: 'int | None' = None, log: 'bool' = True, subset: 'bool' = True, copy: 'bool' = False, **_lotus_extras) -> 'AnnData | np.recarray | None':
    _lotus_kwargs = {}
    if flavor != 'seurat':
        _lotus_kwargs['flavor'] = flavor
    if min_disp is not None:
        _lotus_kwargs['min_disp'] = min_disp
    if max_disp is not None:
        _lotus_kwargs['max_disp'] = max_disp
    if min_mean is not None:
        _lotus_kwargs['min_mean'] = min_mean
    if max_mean is not None:
        _lotus_kwargs['max_mean'] = max_mean
    if n_bins != 20:
        _lotus_kwargs['n_bins'] = n_bins
    if n_top_genes is not None:
        _lotus_kwargs['n_top_genes'] = n_top_genes
    if log != True:
        _lotus_kwargs['log'] = log
    if subset != True:
        _lotus_kwargs['subset'] = subset
    if copy != False:
        _lotus_kwargs['copy'] = copy
    _lotus_call_args = []
    if data is not None:
        _lotus_call_args.append(data)
    return _orig_module.filter_genes_dispersion(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def filter_genes_fano_deprecated(x, /, e_cutoff, v_cutoff, **_lotus_extras):
    _lotus_call_args = []
    _lotus_call_args.append(x)
    _lotus_call_args.append(e_cutoff)
    _lotus_call_args.append(v_cutoff)
    return _orig_module.filter_genes_fano_deprecated(*_lotus_call_args, **_lotus_extras)

def materialize_as_ndarray(a: 'DaskArray | ArrayLike | tuple[ArrayLike | ZappyArray | DaskArray, ...]' = None, **_lotus_extras) -> 'tuple[np.ndarray] | np.ndarray':
    _lotus_call_args = []
    if a is not None:
        _lotus_call_args.append(a)
    return _orig_module.materialize_as_ndarray(*_lotus_call_args, **_lotus_extras)

def __getattr__(name: str):
    try:
        return getattr(_orig_module, name)
    except AttributeError as exc:
        raise AttributeError(f"scanpy.preprocessing._deprecated.highly_variable_genes has no attribute {name!r}") from exc

def __dir__():
    return sorted(set(__all__) | {name for name in dir(_orig_module) if not name.startswith('__')})
