# Auto-generated by scripts/generate_scanpy_proxies.py
from __future__ import annotations

import inspect

import scanpy.preprocessing._deprecated.sampling as _orig_module

__all__ = [
    "legacy_numpy_gen",
    "sample",
    "subsample"
]

def legacy_numpy_gen(random_state: '_LegacyRandom | None' = None, **_lotus_extras) -> 'np.random.Generator':
    _lotus_call_args = []
    _lotus_call_args.append(random_state)
    return _orig_module.legacy_numpy_gen(*_lotus_call_args, **_lotus_extras)

def sample(data: 'AnnData | np.ndarray | CSBase | DaskArray' = None, fraction: 'float | None' = None, *, n: 'int | None' = None, rng: 'RNGLike | SeedLike | None' = None, copy: 'bool' = False, replace: 'bool' = False, axis: "Literal['obs', 0, 'var', 1]" = 'obs', p: 'str | NDArray[np.bool_] | NDArray[np.floating] | None' = None, **_lotus_extras) -> 'AnnData | None | tuple[np.ndarray | CSBase | DaskArray, NDArray[np.int64]]':
    _lotus_kwargs = {}
    if n is not None:
        _lotus_kwargs['n'] = n
    if rng is not None:
        _lotus_kwargs['rng'] = rng
    if copy != False:
        _lotus_kwargs['copy'] = copy
    if replace != False:
        _lotus_kwargs['replace'] = replace
    if axis != 'obs':
        _lotus_kwargs['axis'] = axis
    if p is not None:
        _lotus_kwargs['p'] = p
    _lotus_call_args = []
    if data is not None:
        _lotus_call_args.append(data)
    _lotus_call_args.append(fraction)
    return _orig_module.sample(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def subsample(data: 'AnnData | np.ndarray | CSBase' = None, fraction: 'float | None' = None, *, n_obs: 'int | None' = None, random_state: '_LegacyRandom' = 0, copy: 'bool' = False, **_lotus_extras) -> 'AnnData | tuple[np.ndarray | CSBase, NDArray[np.int64]] | None':
    _lotus_kwargs = {}
    if n_obs is not None:
        _lotus_kwargs['n_obs'] = n_obs
    if random_state != 0:
        _lotus_kwargs['random_state'] = random_state
    if copy != False:
        _lotus_kwargs['copy'] = copy
    _lotus_call_args = []
    if data is not None:
        _lotus_call_args.append(data)
    _lotus_call_args.append(fraction)
    return _orig_module.subsample(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def __getattr__(name: str):
    try:
        return getattr(_orig_module, name)
    except AttributeError as exc:
        raise AttributeError(f"scanpy.preprocessing._deprecated.sampling has no attribute {name!r}") from exc

def __dir__():
    return sorted(set(__all__) | {name for name in dir(_orig_module) if not name.startswith('__')})
