# Auto-generated by scripts/generate_scanpy_proxies.py
from __future__ import annotations

import inspect

import scanpy.experimental.pp as _orig_module

__all__ = [
    "highly_variable_genes",
    "normalize_pearson_residuals",
    "normalize_pearson_residuals_pca",
    "recipe_pearson_residuals"
]

def highly_variable_genes(adata: 'AnnData' = None, *, theta: 'float' = 100, clip: 'float | None' = None, n_top_genes: 'int | None' = None, batch_key: 'str | None' = None, chunksize: 'int' = 1000, flavor: "Literal['pearson_residuals']" = 'pearson_residuals', check_values: 'bool' = True, layer: 'str | None' = None, subset: 'bool' = False, inplace: 'bool' = True, **_lotus_extras) -> 'pd.DataFrame | None':
    _lotus_kwargs = {}
    if theta != 100:
        _lotus_kwargs['theta'] = theta
    if clip is not None:
        _lotus_kwargs['clip'] = clip
    if n_top_genes is not None:
        _lotus_kwargs['n_top_genes'] = n_top_genes
    if batch_key is not None:
        _lotus_kwargs['batch_key'] = batch_key
    if chunksize != 1000:
        _lotus_kwargs['chunksize'] = chunksize
    if flavor != 'pearson_residuals':
        _lotus_kwargs['flavor'] = flavor
    if check_values != True:
        _lotus_kwargs['check_values'] = check_values
    if layer is not None:
        _lotus_kwargs['layer'] = layer
    if subset != False:
        _lotus_kwargs['subset'] = subset
    if inplace != True:
        _lotus_kwargs['inplace'] = inplace
    _lotus_call_args = []
    if adata is not None:
        _lotus_call_args.append(adata)
    return _orig_module.highly_variable_genes(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def normalize_pearson_residuals(adata: 'AnnData' = None, *, theta: 'float' = 100, clip: 'float | None' = None, check_values: 'bool' = True, layer: 'str | None' = None, inplace: 'bool' = True, copy: 'bool' = False, **_lotus_extras) -> 'AnnData | dict[str, np.ndarray] | None':
    _lotus_kwargs = {}
    if theta != 100:
        _lotus_kwargs['theta'] = theta
    if clip is not None:
        _lotus_kwargs['clip'] = clip
    if check_values != True:
        _lotus_kwargs['check_values'] = check_values
    if layer is not None:
        _lotus_kwargs['layer'] = layer
    if inplace != True:
        _lotus_kwargs['inplace'] = inplace
    if copy != False:
        _lotus_kwargs['copy'] = copy
    _lotus_call_args = []
    if adata is not None:
        _lotus_call_args.append(adata)
    return _orig_module.normalize_pearson_residuals(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

_normalize_pearson_residuals_pca_kwargs_pca_default = inspect.signature(_orig_module.normalize_pearson_residuals_pca).parameters['kwargs_pca'].default
_normalize_pearson_residuals_pca_mask_var_default = inspect.signature(_orig_module.normalize_pearson_residuals_pca).parameters['mask_var'].default

def normalize_pearson_residuals_pca(adata: 'AnnData' = None, *, theta: 'float' = 100, clip: 'float | None' = None, n_comps: 'int | None' = 50, random_state: 'float' = 0, kwargs_pca: 'Mapping[str, Any]' = _normalize_pearson_residuals_pca_kwargs_pca_default, mask_var: 'np.ndarray | str | None | Empty' = _normalize_pearson_residuals_pca_mask_var_default, use_highly_variable: 'bool | None' = None, check_values: 'bool' = True, inplace: 'bool' = True, **_lotus_extras) -> 'AnnData | None':
    _lotus_kwargs = {}
    if theta != 100:
        _lotus_kwargs['theta'] = theta
    if clip is not None:
        _lotus_kwargs['clip'] = clip
    if n_comps != 50:
        _lotus_kwargs['n_comps'] = n_comps
    if random_state != 0:
        _lotus_kwargs['random_state'] = random_state
    if kwargs_pca is not _normalize_pearson_residuals_pca_kwargs_pca_default:
        _lotus_kwargs['kwargs_pca'] = kwargs_pca
    if mask_var is not _normalize_pearson_residuals_pca_mask_var_default:
        _lotus_kwargs['mask_var'] = mask_var
    if use_highly_variable is not None:
        _lotus_kwargs['use_highly_variable'] = use_highly_variable
    if check_values != True:
        _lotus_kwargs['check_values'] = check_values
    if inplace != True:
        _lotus_kwargs['inplace'] = inplace
    _lotus_call_args = []
    if adata is not None:
        _lotus_call_args.append(adata)
    return _orig_module.normalize_pearson_residuals_pca(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

_recipe_pearson_residuals_kwargs_pca_default = inspect.signature(_orig_module.recipe_pearson_residuals).parameters['kwargs_pca'].default

def recipe_pearson_residuals(adata: 'AnnData' = None, *, theta: 'float' = 100, clip: 'float | None' = None, n_top_genes: 'int' = 1000, batch_key: 'str | None' = None, chunksize: 'int' = 1000, n_comps: 'int | None' = 50, random_state: 'float | None' = 0, kwargs_pca: 'Mapping[str, Any]' = _recipe_pearson_residuals_kwargs_pca_default, check_values: 'bool' = True, inplace: 'bool' = True, **_lotus_extras) -> 'tuple[AnnData, pd.DataFrame] | None':
    _lotus_kwargs = {}
    if theta != 100:
        _lotus_kwargs['theta'] = theta
    if clip is not None:
        _lotus_kwargs['clip'] = clip
    if n_top_genes != 1000:
        _lotus_kwargs['n_top_genes'] = n_top_genes
    if batch_key is not None:
        _lotus_kwargs['batch_key'] = batch_key
    if chunksize != 1000:
        _lotus_kwargs['chunksize'] = chunksize
    if n_comps != 50:
        _lotus_kwargs['n_comps'] = n_comps
    if random_state != 0:
        _lotus_kwargs['random_state'] = random_state
    if kwargs_pca is not _recipe_pearson_residuals_kwargs_pca_default:
        _lotus_kwargs['kwargs_pca'] = kwargs_pca
    if check_values != True:
        _lotus_kwargs['check_values'] = check_values
    if inplace != True:
        _lotus_kwargs['inplace'] = inplace
    _lotus_call_args = []
    if adata is not None:
        _lotus_call_args.append(adata)
    return _orig_module.recipe_pearson_residuals(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def __getattr__(name: str):
    try:
        return getattr(_orig_module, name)
    except AttributeError as exc:
        raise AttributeError(f"scanpy.experimental.pp has no attribute {name!r}") from exc

def __dir__():
    return sorted(set(__all__) | {name for name in dir(_orig_module) if not name.startswith('__')})
