# Auto-generated by scripts/generate_scanpy_proxies.py
from __future__ import annotations

import inspect

import scanpy._utils.random as _orig_module

__all__ = [
    "ensure_igraph",
    "ith_k_tuple",
    "legacy_numpy_gen",
    "random_k_tuples",
    "random_str",
    "set_igraph_random_state"
]

def ensure_igraph(**_lotus_extras) -> 'None':
    _lotus_call_args = []
    return _orig_module.ensure_igraph(*_lotus_call_args, **_lotus_extras)

def ith_k_tuple(indices: 'NDArray[np.integer]', /, *, n: 'int', k: 'int', **_lotus_extras) -> 'NDArray[np.int64]':
    _lotus_kwargs = {}
    _lotus_kwargs['n'] = n
    _lotus_kwargs['k'] = k
    _lotus_call_args = []
    _lotus_call_args.append(indices)
    return _orig_module.ith_k_tuple(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def legacy_numpy_gen(random_state: '_LegacyRandom | None' = None, **_lotus_extras) -> 'np.random.Generator':
    _lotus_call_args = []
    _lotus_call_args.append(random_state)
    return _orig_module.legacy_numpy_gen(*_lotus_call_args, **_lotus_extras)

def random_k_tuples(size: 'int' = None, *, n: 'int', k: 'int', rng: 'SeedLike | RNGLike | None' = None, **_lotus_extras) -> 'NDArray[np.int64]':
    _lotus_kwargs = {}
    _lotus_kwargs['n'] = n
    _lotus_kwargs['k'] = k
    if rng is not None:
        _lotus_kwargs['rng'] = rng
    _lotus_call_args = []
    if size is not None:
        _lotus_call_args.append(size)
    return _orig_module.random_k_tuples(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def random_str(size: 'int' = 1, *, length: 'int', alphabet: 'str', rng: 'SeedLike | RNGLike | None' = None, **_lotus_extras) -> 'NDArray[np.str_]':
    _lotus_kwargs = {}
    _lotus_kwargs['length'] = length
    _lotus_kwargs['alphabet'] = alphabet
    if rng is not None:
        _lotus_kwargs['rng'] = rng
    _lotus_call_args = []
    _lotus_call_args.append(size)
    return _orig_module.random_str(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def set_igraph_random_state(random_state: 'int | np.random.RandomState' = None, **_lotus_extras) -> 'Generator[None, None, None]':
    _lotus_call_args = []
    if random_state is not None:
        _lotus_call_args.append(random_state)
    return _orig_module.set_igraph_random_state(*_lotus_call_args, **_lotus_extras)

def __getattr__(name: str):
    try:
        return getattr(_orig_module, name)
    except AttributeError as exc:
        raise AttributeError(f"scanpy._utils.random has no attribute {name!r}") from exc

def __dir__():
    return sorted(set(__all__) | {name for name in dir(_orig_module) if not name.startswith('__')})
