# Auto-generated by scripts/generate_scanpy_proxies.py
from __future__ import annotations

import inspect

import scanpy.neighbors._backends.rapids as _orig_module

__all__ = [
    "RapidsKNNTransformer",
    "TransformerChecksMixin",
    "settings"
]

class RapidsKNNTransformer(_orig_module.RapidsKNNTransformer):
    def __init__(self, *, handle=None, algorithm: "_Algorithm | Literal['auto']" = 'auto', n_neighbors: 'int', metric: '_Metric' = 'euclidean', p: 'int' = 2, algo_params: 'Mapping[str, Any] | None' = None, metric_params: 'Mapping[str, Any] | None' = None, random_state=None) -> 'None':
        super().__init__(handle=handle, algorithm=algorithm, n_neighbors=n_neighbors, metric=metric, p=p, algo_params=algo_params, metric_params=metric_params, random_state=random_state)

class TransformerChecksMixin(_orig_module.TransformerChecksMixin):
    def __init__(self, /, *args, **kwargs):
        super().__init__(*args, **kwargs)

class settings(_orig_module.settings):
    def __init__(self, /, *args, **kwargs):
        super().__init__(*args, **kwargs)

def __getattr__(name: str):
    try:
        return getattr(_orig_module, name)
    except AttributeError as exc:
        raise AttributeError(f"scanpy.neighbors._backends.rapids has no attribute {name!r}") from exc

def __dir__():
    return sorted(set(__all__) | {name for name in dir(_orig_module) if not name.startswith('__')})
