# Auto-generated by scripts/generate_scanpy_proxies.py
from __future__ import annotations

import inspect

import scanpy.queries as _orig_module

__all__ = [
    "biomart_annotations",
    "enrich",
    "gene_coordinates",
    "mitochondrial_genes"
]

def biomart_annotations(org: 'str', attrs: 'Iterable[str]', *, host: 'str' = 'www.ensembl.org', use_cache: 'bool' = False, **_lotus_extras) -> 'pd.DataFrame':
    _lotus_kwargs = {}
    if host != 'www.ensembl.org':
        _lotus_kwargs['host'] = host
    if use_cache != False:
        _lotus_kwargs['use_cache'] = use_cache
    _lotus_call_args = []
    _lotus_call_args.append(org)
    _lotus_call_args.append(attrs)
    return _orig_module.biomart_annotations(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

_enrich_gprofiler_kwargs_default = inspect.signature(_orig_module.enrich).parameters['gprofiler_kwargs'].default

def enrich(container: 'Iterable[str] | Mapping[str, Iterable[str]]' = None, *, org: 'str' = 'hsapiens', gprofiler_kwargs: 'Mapping[str, Any]' = _enrich_gprofiler_kwargs_default, **_lotus_extras) -> 'pd.DataFrame':
    _lotus_kwargs = {}
    if org != 'hsapiens':
        _lotus_kwargs['org'] = org
    if gprofiler_kwargs is not _enrich_gprofiler_kwargs_default:
        _lotus_kwargs['gprofiler_kwargs'] = gprofiler_kwargs
    _lotus_call_args = []
    if container is not None:
        _lotus_call_args.append(container)
    return _orig_module.enrich(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def gene_coordinates(org: 'str', gene_name: 'str', *, gene_attr: 'str' = 'external_gene_name', chr_exclude: 'Iterable[str]' = (), host: 'str' = 'www.ensembl.org', use_cache: 'bool' = False, **_lotus_extras) -> 'pd.DataFrame':
    _lotus_kwargs = {}
    if gene_attr != 'external_gene_name':
        _lotus_kwargs['gene_attr'] = gene_attr
    if chr_exclude != ():
        _lotus_kwargs['chr_exclude'] = chr_exclude
    if host != 'www.ensembl.org':
        _lotus_kwargs['host'] = host
    if use_cache != False:
        _lotus_kwargs['use_cache'] = use_cache
    _lotus_call_args = []
    _lotus_call_args.append(org)
    _lotus_call_args.append(gene_name)
    return _orig_module.gene_coordinates(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def mitochondrial_genes(org: 'str' = None, *, attrname: 'str' = 'external_gene_name', host: 'str' = 'www.ensembl.org', use_cache: 'bool' = False, chromosome: 'str' = 'MT', **_lotus_extras) -> 'pd.DataFrame':
    _lotus_kwargs = {}
    if attrname != 'external_gene_name':
        _lotus_kwargs['attrname'] = attrname
    if host != 'www.ensembl.org':
        _lotus_kwargs['host'] = host
    if use_cache != False:
        _lotus_kwargs['use_cache'] = use_cache
    if chromosome != 'MT':
        _lotus_kwargs['chromosome'] = chromosome
    _lotus_call_args = []
    if org is not None:
        _lotus_call_args.append(org)
    return _orig_module.mitochondrial_genes(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def __getattr__(name: str):
    try:
        return getattr(_orig_module, name)
    except AttributeError as exc:
        raise AttributeError(f"scanpy.queries has no attribute {name!r}") from exc

def __dir__():
    return sorted(set(__all__) | {name for name in dir(_orig_module) if not name.startswith('__')})
