# Auto-generated by scripts/generate_scanpy_proxies.py
from __future__ import annotations

import inspect

import scanpy.logging as _orig_module

__all__ = [
    "debug",
    "error",
    "hint",
    "info",
    "print_header",
    "print_version_and_date",
    "print_versions",
    "warning"
]

def debug(msg: 'str' = None, *, time: 'datetime | None' = None, deep: 'str | None' = None, extra: 'dict | None' = None, **_lotus_extras) -> 'datetime':
    _lotus_kwargs = {}
    if time is not None:
        _lotus_kwargs['time'] = time
    if deep is not None:
        _lotus_kwargs['deep'] = deep
    if extra is not None:
        _lotus_kwargs['extra'] = extra
    _lotus_call_args = []
    if msg is not None:
        _lotus_call_args.append(msg)
    return _orig_module.debug(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def error(msg: 'str' = None, *, time: 'datetime | None' = None, deep: 'str | None' = None, extra: 'dict | None' = None, **_lotus_extras) -> 'datetime':
    _lotus_kwargs = {}
    if time is not None:
        _lotus_kwargs['time'] = time
    if deep is not None:
        _lotus_kwargs['deep'] = deep
    if extra is not None:
        _lotus_kwargs['extra'] = extra
    _lotus_call_args = []
    if msg is not None:
        _lotus_call_args.append(msg)
    return _orig_module.error(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def hint(msg: 'str' = None, *, time: 'datetime | None' = None, deep: 'str | None' = None, extra: 'dict | None' = None, **_lotus_extras) -> 'datetime':
    _lotus_kwargs = {}
    if time is not None:
        _lotus_kwargs['time'] = time
    if deep is not None:
        _lotus_kwargs['deep'] = deep
    if extra is not None:
        _lotus_kwargs['extra'] = extra
    _lotus_call_args = []
    if msg is not None:
        _lotus_call_args.append(msg)
    return _orig_module.hint(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def info(msg: 'str' = None, *, time: 'datetime | None' = None, deep: 'str | None' = None, extra: 'dict | None' = None, **_lotus_extras) -> 'datetime':
    _lotus_kwargs = {}
    if time is not None:
        _lotus_kwargs['time'] = time
    if deep is not None:
        _lotus_kwargs['deep'] = deep
    if extra is not None:
        _lotus_kwargs['extra'] = extra
    _lotus_call_args = []
    if msg is not None:
        _lotus_call_args.append(msg)
    return _orig_module.info(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def print_header(*, file: 'IO[str] | None' = None, **_lotus_extras):
    _lotus_kwargs = {}
    if file is not None:
        _lotus_kwargs['file'] = file
    _lotus_call_args = []
    return _orig_module.print_header(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def print_version_and_date(*, file=None, **_lotus_extras):
    _lotus_kwargs = {}
    if file is not None:
        _lotus_kwargs['file'] = file
    _lotus_call_args = []
    return _orig_module.print_version_and_date(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def print_versions(**_lotus_extras) -> 'SessionInfo':
    _lotus_call_args = []
    return _orig_module.print_versions(*_lotus_call_args, **_lotus_extras)

def warning(msg: 'str' = None, *, time: 'datetime | None' = None, deep: 'str | None' = None, extra: 'dict | None' = None, **_lotus_extras) -> 'datetime':
    _lotus_kwargs = {}
    if time is not None:
        _lotus_kwargs['time'] = time
    if deep is not None:
        _lotus_kwargs['deep'] = deep
    if extra is not None:
        _lotus_kwargs['extra'] = extra
    _lotus_call_args = []
    if msg is not None:
        _lotus_call_args.append(msg)
    return _orig_module.warning(*_lotus_call_args, **_lotus_kwargs, **_lotus_extras)

def __getattr__(name: str):
    try:
        return getattr(_orig_module, name)
    except AttributeError as exc:
        raise AttributeError(f"scanpy.logging has no attribute {name!r}") from exc

def __dir__():
    return sorted(set(__all__) | {name for name in dir(_orig_module) if not name.startswith('__')})

import sys
import scanpy._settings as _orig_settings_mod

def _lotus__wrap_logging(name: str):
    orig = getattr(_orig_module, name)

    def wrapper(msg, *, time=None, deep=None, extra=None):
        lotus_module = sys.modules.get("lotus")
        if lotus_module is None or not hasattr(lotus_module, "settings"):
            raise RuntimeError("lotus.settings is not available")
        _lotus_settings = lotus_module.settings
        method = getattr(_lotus_settings._root_logger, name)
        old_settings = getattr(_orig_settings_mod, "settings", None)
        have_datetime = "datetime" in globals()
        old_datetime = getattr(_orig_module, "datetime", None)
        try:
            _orig_settings_mod.settings = _lotus_settings
            if have_datetime:
                _orig_module.datetime = globals()["datetime"]
            return method(msg, time=time, deep=deep, extra=extra)
        finally:
            if old_settings is not None:
                _orig_settings_mod.settings = old_settings
            if have_datetime and old_datetime is not None:
                _orig_module.datetime = old_datetime

    wrapper.__doc__ = orig.__doc__
    wrapper.__signature__ = inspect.signature(orig)
    return wrapper

for _name in ("debug", "error", "hint", "info", "warning"):
    globals()[_name] = _lotus__wrap_logging(_name)

del _lotus__wrap_logging
